import Phaser from 'phaser';
import './style.css';

type Tool = 'hoe'|'seed'|'water'|'harvest'|'hand';
type Weather = '晴れ'|'曇り'|'雨'|'嵐'|'雷雨';
type CropState = 'growing'|'ready'|'shocked';
interface Crop { kind:string; plantedAt:number; growMs:number; watered:boolean; state:CropState; shockAt?:number; pausedMs:number; }
interface PlotSave { tilled:boolean; crop?:Crop }
interface SaveData { version:number; coins:number; seeds:Record<string,number>; inventory:Record<string,number>; plots:PlotSave[]; weather:Weather; weatherAt:number; lightningCount:number; rodLevel:number; barnLevel:number; storageLevel:number; toolLevel:number; tutorialStep:number; lightningTutorial:boolean; reducedFlash:boolean; thunderVolume:number; masterVolume:number; leftHanded:boolean; lastSeen:number; maxSeen:number; animals:Record<string,number>; animalAt:number; dailySold:number }

const CROPS=[
  ['にんじん','🥕',25000,24],['かぶ','🌱',35000,32],['じゃがいも','🥔',45000,42],['トマト','🍅',55000,54],['とうもろこし','🌽',70000,68],['いちご','🍓',80000,80],['かぼちゃ','🎃',95000,98],['なす','🍆',60000,58],['キャベツ','🥬',75000,74],['ひまわり','🌻',90000,90],['メロン','🍈',110000,115],['ブルーベリー','🫐',100000,105]
] as const;
const DEFAULT:SaveData={version:1,coins:180,seeds:{'にんじん':6},inventory:{},plots:Array.from({length:18},()=>({tilled:false})),weather:'晴れ',weatherAt:Date.now(),lightningCount:0,rodLevel:0,barnLevel:1,storageLevel:1,toolLevel:1,tutorialStep:0,lightningTutorial:false,reducedFlash:false,thunderVolume:.7,masterVolume:.7,leftHanded:false,lastSeen:Date.now(),maxSeen:Date.now(),animals:{'ニワトリ':1,'ウシ':1,'ヒツジ':1},animalAt:Date.now(),dailySold:0};
const cloneDefault=()=>JSON.parse(JSON.stringify(DEFAULT)) as SaveData;

class SaveStore {
  db?:IDBDatabase;
  async init(){return new Promise<void>(resolve=>{const q=indexedDB.open('hidamari-farm',1);q.onupgradeneeded=()=>q.result.createObjectStore('saves');q.onsuccess=()=>{this.db=q.result;resolve()};q.onerror=()=>resolve()})}
  async load():Promise<SaveData>{await this.init();const fromLocal=()=>{try{return JSON.parse(localStorage.getItem('hidamari-backup')||'null')}catch{return null}};if(!this.db)return fromLocal()||cloneDefault();return new Promise(res=>{const q=this.db!.transaction('saves').objectStore('saves').get('main');q.onsuccess=()=>res(q.result||fromLocal()||cloneDefault());q.onerror=()=>res(fromLocal()||cloneDefault())})}
  save(data:SaveData){data.lastSeen=Date.now();data.maxSeen=Math.max(data.maxSeen||0,data.lastSeen);localStorage.setItem('hidamari-backup',JSON.stringify(data));if(this.db)this.db.transaction('saves','readwrite').objectStore('saves').put(data,'main')}
  clear(){localStorage.removeItem('hidamari-backup');if(this.db)this.db.transaction('saves','readwrite').objectStore('saves').delete('main')}
}
const store=new SaveStore();
let game:Phaser.Game;

document.querySelector('#app')!.innerHTML='<div class="game-shell"><div class="game-wrap" id="wrap"><div id="game"></div><div class="hud"><div class="top-left"><div class="pill" id="coins">🪙 0</div><div class="pill weather" id="weather">☀️ 晴れ</div><div class="pill" id="quest">📦 はじめての収穫 0/1</div></div><button class="tool" id="settings" aria-label="設定">⚙️</button></div><div class="toolbar" id="toolbar"></div><div class="joystick" id="joy"><div class="stick" id="stick"></div></div><button class="action" id="action">つかう</button></div></div>';

let save=cloneDefault(), activeTool:Tool='hoe', activeSeed='にんじん', gameScene:FarmScene|undefined;
const toolData:[Tool,string,string][]=[['hoe','⛏️','耕す'],['seed','🌱','植える'],['water','💧','水やり'],['harvest','🧺','収穫'],['hand','✋','調べる']];
const toolbar=document.querySelector('#toolbar')!;
const drawToolbar=()=>{toolbar.innerHTML=toolData.map(([id,icon,label])=>`<button class="tool ${activeTool===id?'active':''}" data-tool="${id}"><span>${icon}</span>${label}</button>`).join('');toolbar.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{activeTool=(b as HTMLElement).dataset.tool as Tool;drawToolbar()}))};drawToolbar();
const ui=()=>{document.querySelector('#coins')!.textContent=`🪙 ${save.coins}`;const icons:Record<Weather,string>={'晴れ':'☀️','曇り':'☁️','雨':'🌧️','嵐':'🌪️','雷雨':'⛈️'};document.querySelector('#weather')!.textContent=`${icons[save.weather]} ${save.weather}`;document.querySelector('#quest')!.textContent=save.dailySold?`✅ はじめての販売 達成！`:'📦 はじめての販売 0/1'};
const toast=(s:string,ms=2300)=>{const wrap=document.querySelector('#wrap')!;wrap.querySelector('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.textContent=s;wrap.append(e);setTimeout(()=>e.remove(),ms)};
const panel=(html:string)=>{const e=document.createElement('div');e.className='panel-backdrop';e.innerHTML=`<div class="panel">${html}</div>`;document.querySelector('#wrap')!.append(e);e.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>e.remove()));return e};

class FarmScene extends Phaser.Scene {
  player!:Phaser.GameObjects.Container; plots:Phaser.GameObjects.Container[]=[]; keys!:Record<string,Phaser.Input.Keyboard.Key>; joy={x:0,y:0}; lastAutosave=0; stormShade?:Phaser.GameObjects.Rectangle; rain:Phaser.GameObjects.Group|null=null; nextStrike=0;
  constructor(){super('farm')}
  preload(){this.load.image('title','/assets/farm-title.png')}
  create(){
    gameScene=this;this.cameras.main.setBackgroundColor('#7ed8ef');this.makeTextures();this.drawWorld();
    this.player=this.add.container(260,350,[this.add.ellipse(0,20,30,15,0x18382b,.25),this.add.circle(0,0,18,0xffc599),this.add.rectangle(0,23,30,36,0x4d7ec7),this.add.rectangle(0,-15,42,11,0xeebc4d),this.add.rectangle(0,-9,30,9,0x9a6838)]).setDepth(20);
    this.keys=this.input.keyboard!.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT,E,T') as Record<string,Phaser.Input.Keyboard.Key>;
    this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(p.y<600)this.useNearest(p.worldX,p.worldY)});
    this.setupTouch();this.applyOffline();this.setWeather(save.weather,true);this.time.addEvent({delay:1000,loop:true,callback:()=>this.tick()});
    if(save.tutorialStep===0)this.tutorial();ui();
  }
  makeTextures(){const g=this.make.graphics({x:0,y:0},false);g.fillStyle(0x4f9c56).fillRect(0,0,64,64);g.fillStyle(0x58aa5e).fillRect(0,0,32,32).fillRect(32,32,32,32);g.generateTexture('grass',64,64);g.destroy()}
  drawWorld(){
    this.add.image(640,360,'title').setDisplaySize(1280,720).setDepth(-10);this.add.rectangle(640,470,1280,500,0x287343,.28).setDepth(-5);this.add.rectangle(640,290,1280,65,0xd9b66d,.88);this.add.rectangle(640,285,1280,10,0xffdf94,.9);
    this.building(80,220,'🏪','たね屋');this.building(1160,220,'💰','出荷箱');this.building(1040,445,'🏠','小屋');this.add.text(990,490,'🐔  🐄  🐑',{fontSize:'30px'}).setDepth(2);
    for(let i=0;i<18;i++){const col=i%6,row=Math.floor(i/6),x=400+col*78,y=380+row*78;const c=this.add.container(x,y);c.setSize(68,62);c.setInteractive();c.on('pointerdown',(p:Phaser.Input.Pointer)=>{p.event.stopPropagation();this.interactPlot(i)});this.plots.push(c);this.redrawPlot(i)}
    this.add.text(22,655,'WASD / 矢印: 移動　E: 使う　T: 雷雨テスト',{fontFamily:'sans-serif',fontSize:'15px',color:'#17324a',backgroundColor:'#ffffffaa',padding:{x:7,y:4}}).setDepth(30);
    if(save.rodLevel>0)this.drawRod();
  }
  building(x:number,y:number,emoji:string,label:string){const c=this.add.container(x,y,[this.add.rectangle(0,25,105,80,0xf9e4b4).setStrokeStyle(5,0x925b3d),this.add.triangle(0,-30,-65,0,65,0,0,-60,0xb95745),this.add.text(0,8,emoji,{fontSize:'34px'}).setOrigin(.5),this.add.text(0,65,label,{fontSize:'16px',fontStyle:'bold',color:'#253d37',backgroundColor:'#fff8',padding:{x:5,y:2}}).setOrigin(.5)]).setDepth(3).setSize(120,130).setInteractive();c.on('pointerdown',(p:Phaser.Input.Pointer)=>{p.event.stopPropagation();label==='たね屋'?openShop():label==='出荷箱'?openShipping():openAnimals()})}
  drawRod(){const x=860,y=425;this.add.rectangle(x,y,8,110,0x6c7781).setDepth(8);this.add.triangle(x,y-70,-20,20,20,20,0,-18,0xe6c34f).setDepth(9);this.add.circle(x,y-20,130+save.rodLevel*35,0x78d4ff,.08).setStrokeStyle(2,0x78d4ff,.35).setDepth(2);this.add.text(x,y+65,`避雷針 Lv.${save.rodLevel}`,{fontSize:'13px',color:'#17324a',backgroundColor:'#ffffffaa'}).setOrigin(.5).setDepth(10)}
  redrawPlot(i:number){const c=this.plots[i];c.removeAll(true);const p=save.plots[i];c.add(this.add.rectangle(0,0,68,58,p.tilled?0x8a583b:0x518f46).setStrokeStyle(3,p.tilled?0xb8875c:0x73b965));if(!p.crop)return;const crop=p.crop,def=CROPS.find(x=>x[0]===crop.kind)!;let icon=def[1],size=26;if(crop.state==='growing'){const progress=this.progress(crop);icon=progress>.65?def[1]:'🌱';size=progress>.65?24:20}c.add(this.add.text(0,-3,icon,{fontSize:`${size}px`}).setOrigin(.5));if(crop.watered)c.add(this.add.circle(24,20,5,0x64caff));if(crop.state==='ready')c.add(this.add.text(20,-24,'✨',{fontSize:'14px'}));if(crop.state==='shocked'){c.add(this.add.rectangle(0,19,58,8,0x3b302a,.9));c.add(this.add.text(0,-24,'⚡⏸',{fontSize:'17px'}).setOrigin(.5));}}
  progress(c:Crop){const elapsed=(c.state==='shocked'?c.shockAt!:Date.now())-c.plantedAt-c.pausedMs;return Math.min(1,elapsed/(c.watered?c.growMs:c.growMs*2))}
  interactPlot(i:number){const p=save.plots[i];if(activeTool==='hoe'){if(!p.tilled&&!p.crop){p.tilled=true;toast('ふかふかの土になった！');save.tutorialStep=Math.max(1,save.tutorialStep)}else toast('ここはもう耕してあるよ')}else if(activeTool==='seed'){if(!p.tilled)return toast('先に土を耕そう');if(p.crop)return toast('ここには作物があるよ');if((save.seeds[activeSeed]||0)<1)return toast('種がないよ。たね屋で買おう');const d=CROPS.find(x=>x[0]===activeSeed)!;save.seeds[activeSeed]--;p.crop={kind:activeSeed,plantedAt:Date.now(),growMs:d[2],watered:false,state:'growing',pausedMs:0};save.tutorialStep=Math.max(2,save.tutorialStep);toast(`${activeSeed}を植えた！`)}else if(activeTool==='water'){if(!p.crop)return toast('作物が植わっていないよ');if(p.crop.state==='shocked'){if(save.weather==='雷雨')return toast('雷雨が止んでから手動で水をあげよう');p.crop.pausedMs+=Date.now()-p.crop.shockAt!;p.crop.shockAt=undefined;p.crop.state='growing';p.crop.watered=true;toast('💧 感電から回復！ 成長を再開した');}else{p.crop.watered=true;toast('水をあげた！');save.tutorialStep=Math.max(3,save.tutorialStep)}}else if(activeTool==='harvest'){if(!p.crop||p.crop.state!=='ready')return toast('まだ収穫できないよ');save.inventory[p.crop.kind]=(save.inventory[p.crop.kind]||0)+1;toast(`${p.crop.kind}を収穫した！ 出荷箱へ持っていこう`);p.crop=undefined;save.tutorialStep=4}else if(activeTool==='hand'){if(p.crop?.state==='shocked')toast('⚡ 成長停止中。雷雨が止んだら水をあげると回復');else if(p.crop)toast(p.crop.state==='ready'?'収穫できるよ！':`成長度 ${Math.floor(this.progress(p.crop)*100)}%`);else toast('何も植わっていない')};this.redrawPlot(i);store.save(save);ui()}
  useNearest(x=this.player.x,y=this.player.y){let best=-1,dist=100;this.plots.forEach((p,i)=>{const d=Phaser.Math.Distance.Between(x,y,p.x,p.y);if(d<dist){dist=d;best=i}});if(best>=0)this.interactPlot(best)}
  update(_:number,delta:number){let x=0,y=0;if(this.keys.A.isDown||this.keys.LEFT.isDown)x--;if(this.keys.D.isDown||this.keys.RIGHT.isDown)x++;if(this.keys.W.isDown||this.keys.UP.isDown)y--;if(this.keys.S.isDown||this.keys.DOWN.isDown)y++;x+=this.joy.x;y+=this.joy.y;const l=Math.hypot(x,y)||1;this.player.x=Phaser.Math.Clamp(this.player.x+x/l*delta*.18,25,1255);this.player.y=Phaser.Math.Clamp(this.player.y+y/l*delta*.18,250,630);if(Phaser.Input.Keyboard.JustDown(this.keys.E))this.useNearest();if(Phaser.Input.Keyboard.JustDown(this.keys.T))this.setWeather('雷雨');}
  tick(){save.plots.forEach((p,i)=>{if(p.crop?.state==='growing'&&this.progress(p.crop)>=1){p.crop.state='ready';this.redrawPlot(i)}});if(Date.now()-save.weatherAt>120000)this.setWeather(Phaser.Math.RND.pick<Weather>(['晴れ','晴れ','曇り','雨','嵐','雷雨']));if(save.weather==='雷雨'&&Date.now()>this.nextStrike)this.lightning();if(Date.now()-this.lastAutosave>10000){store.save(save);this.lastAutosave=Date.now()}}
  setWeather(w:Weather,restore=false){save.weather=w;save.weatherAt=Date.now();save.lightningCount=0;this.nextStrike=Date.now()+6000;this.stormShade?.destroy();this.rain?.clear(true,true);this.rain=null;if(w==='雨'||w==='嵐'||w==='雷雨'){save.plots.forEach((p,i)=>{if(p.crop&&p.crop.state!=='shocked'){p.crop.watered=true;this.redrawPlot(i)}});this.rain=this.add.group();for(let i=0;i<90;i++){const drop=this.add.rectangle(Math.random()*1280,Math.random()*720,2,14,0xb7e7ff,.65).setDepth(40).setAngle(15);this.rain.add(drop)};this.tweens.add({targets:this.rain.getChildren(),y:'+=760',x:'+=160',duration:900,repeat:-1,delay:this.rain.getChildren().map(()=>Math.random()*-900) as never})}if(w==='雷雨')this.stormShade=this.add.rectangle(640,360,1280,720,0x102346,.48).setDepth(35);if(!restore)toast(`天気が「${w}」に変わった`);store.save(save);ui()}
  lightning(){const cap=Math.min(3,Math.max(1,Math.ceil(save.plots.filter(p=>p.crop).length*.3)));if(save.lightningCount>=cap)return;const candidates=save.plots.map((p,i)=>({p,i})).filter(({p,i})=>p.crop&&p.crop.state==='growing'&&!this.protected(i));if(!candidates.length){toast(save.rodLevel?'⚡ 避雷針が作物を守った！':'⚡ 雷が遠くへ落ちた');this.rodStrike();this.nextStrike=Date.now()+10000;return}const target=Phaser.Math.RND.pick(candidates);const c=this.plots[target.i];this.add.circle(c.x,c.y,38,0xfff8a8,.2).setDepth(45);this.time.delayedCall(500,()=>{if(!save.reducedFlash){const f=document.createElement('div');f.className='flash';document.querySelector('#wrap')!.append(f);setTimeout(()=>f.remove(),650)}this.cameras.main.shake(300,save.reducedFlash?.004:.012);const bolt=this.add.text(c.x,c.y-105,'⚡',{fontSize:'100px'}).setOrigin(.5).setDepth(50);this.tweens.add({targets:bolt,alpha:0,duration:600,onComplete:()=>bolt.destroy()});target.p.crop!.state='shocked';target.p.crop!.shockAt=Date.now();save.lightningCount++;this.redrawPlot(target.i);store.save(save);toast('⚡ 作物が感電して成長が止まった！');if(!save.lightningTutorial){save.lightningTutorial=true;this.time.delayedCall(900,()=>lightningTutorial())}});this.nextStrike=Date.now()+Phaser.Math.Between(9000,15000)}
  protected(i:number){if(!save.rodLevel)return false;const p=this.plots[i];return Phaser.Math.Distance.Between(p.x,p.y,860,425)<130+save.rodLevel*35}
  rodStrike(){if(!save.rodLevel)return;const b=this.add.text(860,300,'⚡',{fontSize:'90px'}).setOrigin(.5).setDepth(50);this.tweens.add({targets:b,alpha:0,y:410,duration:500,onComplete:()=>b.destroy()})}
  applyOffline(){const now=Date.now(),start=Math.max(save.lastSeen||now,Math.min(now,save.maxSeen||now)),offline=Math.min(86400000,Math.max(0,now-start));if(offline>60000)toast(`おかえり！ オフラインで ${Math.floor(offline/60000)}分 経過しました`);save.maxSeen=Math.max(save.maxSeen||0,now)}
  tutorial(){const p=panel('<h1>🌱 ひだまり農園へようこそ！</h1><p>まずは畑で <b>耕す → 植える → 水やり</b>。にんじんは約25秒で育ちます。</p><p>育ったら収穫し、左上の出荷箱で販売しましょう。</p><button data-close>農園をはじめる</button>');p.querySelector('[data-close]')!.addEventListener('click',()=>{save.tutorialStep=1;store.save(save)})}
  setupTouch(){const joy=document.querySelector('#joy') as HTMLElement,stick=document.querySelector('#stick') as HTMLElement;const move=(e:PointerEvent)=>{const r=joy.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),l=Math.max(1,Math.hypot(x,y)),m=Math.min(38,l);this.joy={x:x/l,y:y/l};stick.style.transform=`translate(${x/l*m}px,${y/l*m}px)`};joy.addEventListener('pointerdown',e=>{joy.setPointerCapture(e.pointerId);move(e)});joy.addEventListener('pointermove',e=>{if(joy.hasPointerCapture(e.pointerId))move(e)});joy.addEventListener('pointerup',()=>{this.joy={x:0,y:0};stick.style.transform='' });document.querySelector('#action')!.addEventListener('click',()=>this.useNearest())}
}

function openShop(){const rows=CROPS.map(c=>`<div class="row"><span>${c[1]} ${c[0]}<small>　種:${save.seeds[c[0]]||0}</small></span><button data-buy="${c[0]}">🪙${Math.ceil(c[3]*.3)}で買う</button></div>`).join('');const p=panel(`<h2>🌱 たね屋</h2><p>植える種: <b id="chosen">${activeSeed}</b></p>${rows}<button class="secondary" data-close>閉じる</button>`);p.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',()=>{const name=(b as HTMLElement).dataset.buy!,d=CROPS.find(c=>c[0]===name)!;const price=Math.ceil(d[3]*.3);if(save.coins<price)return toast('コインが足りないよ');save.coins-=price;save.seeds[name]=(save.seeds[name]||0)+1;activeSeed=name;(p.querySelector('#chosen')!).textContent=name;store.save(save);ui();toast(`${name}の種を買った`)}))}
function openShipping(){const items=Object.entries(save.inventory).filter(([,n])=>n>0);const rows=items.length?items.map(([name,n])=>{const d=CROPS.find(c=>c[0]===name)!;return `<div class="row"><span>${d[1]} ${name} × ${n}</span><button data-sell="${name}">🪙${d[3]}で出荷</button></div>`}).join(''):'<p>出荷できるものはまだありません。</p>';const p=panel(`<h2>📦 出荷箱</h2>${rows}<button class="secondary" data-close>閉じる</button>`);p.querySelectorAll('[data-sell]').forEach(b=>b.addEventListener('click',()=>{const name=(b as HTMLElement).dataset.sell!,d=CROPS.find(c=>c[0]===name)!;save.inventory[name]--;save.coins+=d[3];save.dailySold++;store.save(save);ui();b.parentElement!.remove();toast(`${name}を出荷！ +${d[3]}コイン`)}))}
function openAnimals(){const ready=Date.now()-save.animalAt>60000;const products=[['ニワトリ','卵','🥚'],['ウシ','牛乳','🥛'],['ヒツジ','羊毛','🧶']];const rows=products.map(([a,item,ico])=>`<div class="row"><span>${ico} ${a} Lv.${save.animals[a]}</span><button data-care="${item}" ${ready?'':'disabled'}>${ready?'お世話して回収':'休憩中'}</button></div>`).join('');const p=panel(`<h2>🏠 どうぶつ小屋 Lv.${save.barnLevel}</h2><p>1分ごとにお世話をして畜産物を回収できます。</p>${rows}<button data-upgrade>🪙${save.barnLevel*150} 小屋を強化</button><button class="secondary" data-close>閉じる</button>`);p.querySelectorAll('[data-care]').forEach(b=>b.addEventListener('click',()=>{const item=(b as HTMLElement).dataset.care!;save.inventory[item]=(save.inventory[item]||0)+1;save.animalAt=Date.now();store.save(save);toast(`${item}を回収した！`);p.remove()}));p.querySelector('[data-upgrade]')!.addEventListener('click',()=>{const cost=save.barnLevel*150;if(save.coins<cost)return toast('コインが足りないよ');save.coins-=cost;save.barnLevel++;store.save(save);ui();p.remove();toast('小屋を強化した！')})}
function lightningTutorial(){panel('<h2>⚡ 落雷と感電</h2><p>感電した作物は成長が止まりますが、枯れたり品質が下がったりはしません。</p><p><b>雷雨が止んだ後、手動で水やり</b>すると停止地点から再開します。雨の自動水やりでは治りません。</p><p>設備メニューで避雷針を買うと、範囲内の作物を守れます。</p><button data-close>わかった</button>')}
function openSettings(){const p=panel(`<h2>⚙️ 設定と設備</h2><div class="row"><label>全体音量</label><input id="master" type="range" min="0" max="1" step=".1" value="${save.masterVolume}"></div><div class="row"><label>雷鳴音量</label><input id="thunder" type="range" min="0" max="1" step=".1" value="${save.thunderVolume}"></div><div class="row"><label>稲光を軽減</label><input id="flash" type="checkbox" ${save.reducedFlash?'checked':''}></div><div class="row"><label>操作UIを左右反転</label><input id="left" type="checkbox" ${save.leftHanded?'checked':''}></div><p><button data-rod>🪙${120+save.rodLevel*180} 避雷針を${save.rodLevel?'強化':'購入'}</button><button data-help>操作説明</button></p><p><button class="danger" data-reset>セーブ初期化</button><button class="secondary" data-close>閉じる</button></p>`);const sync=()=>{save.masterVolume=+(p.querySelector('#master') as HTMLInputElement).value;save.thunderVolume=+(p.querySelector('#thunder') as HTMLInputElement).value;save.reducedFlash=(p.querySelector('#flash') as HTMLInputElement).checked;save.leftHanded=(p.querySelector('#left') as HTMLInputElement).checked;document.querySelector('#joy')?.classList.toggle('right',save.leftHanded);store.save(save)};p.querySelectorAll('input').forEach(e=>e.addEventListener('input',sync));p.querySelector('[data-help]')!.addEventListener('click',()=>toast('移動して畑へ。道具を選び、畑をクリック /「つかう」で作業します。'));p.querySelector('[data-rod]')!.addEventListener('click',()=>{const cost=120+save.rodLevel*180;if(save.coins<cost)return toast('コインが足りないよ');save.coins-=cost;save.rodLevel++;store.save(save);ui();p.remove();game.scene.stop('farm');game.scene.start('farm');toast('避雷針を設置した！')});p.querySelector('[data-reset]')!.addEventListener('click',()=>{if(confirm('農園のデータを初期化しますか？')){store.clear();location.reload()}})}
document.querySelector('#settings')!.addEventListener('click',openSettings);
['contextmenu','selectstart','dragstart'].forEach(ev=>document.querySelector('#game')!.addEventListener(ev,e=>e.preventDefault()));

async function boot(){const saveLoaded=await store.load();save={...cloneDefault(),...saveLoaded,plots:saveLoaded.plots?.length===18?saveLoaded.plots:cloneDefault().plots};game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1280,height:720,backgroundColor:'#72c86b',pixelArt:true,scene:[FarmScene],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}})}
void boot();window.addEventListener('beforeunload',()=>store.save(save));document.addEventListener('visibilitychange',()=>{if(document.hidden)store.save(save)});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));

